### BONJOUR AMÉLIE, ICI JEAN-HUGUES ROY
### TOUS MES COMMENTAIRES SERONT EN MAJUSCULES ET PRÉCÉDÉS DE 3 # (HASHTAGS)

### EXCELLENT SCRIPT!
### BONNE UTILISATION DE "RANGE", D'UNE BOUCLE, DE CONCATÉNATION, DE LISTES, ET DE CHANGEMENT DE TYPE (DE "INT" À "STR")
### IL NE MANQUAIT QU'UNE CHOSE: CRÉER UNE LISTE POUR Y METTRE TOUTES LES URLS CRÉÉS PAR TA BOUCLE:

laListedAmelie = []

l1 = list(range(20000,30151))
print(l1)

for url in l1: 
    print("https://montrealcampus.ca/?p=" + str(url))

    ### ET TU PEUX UTILISER ".APPEND" POUR AJOUTER CHAQUE NOUVEL URL À TA LISTE:
    laListedAmelie.append("https://montrealcampus.ca/?p=" + str(url))

### JE VOUS DEMANDAIS AUSSI D'AFFICHER LA LISTE APRÈS LA BOUCLE:

print(laListedAmelie)
# print(len(l1)) ### TA LISTE "l1" EST D'UNE LONGUEUR CONNUE, PUISQUE TU L'AS CRÉÉE AVEC UN "RANGE"
print(len(laListedAmelie))

### ENFIN, IL MANQUAIT QUELQUES COMMENTAIRES POUR M'EXPLIQUER CE QUE TU AS FAIT OU VOULU FAIRE. :)